### ISSUE TITLE
Broken on a Pi Zero 2 W and Pi 3

### ISSUE THREAD

**Issue by gavan-x** [astefanutti/kms-glsl#8]
Tested with latest Raspberry Pi OS Bullseye 64 bit and last version of pi Os Buster 64 bit.

![image](https://user-images.githubusercontent.com/40079787/226830587-1f4ef190-11be-4726-9ce9-ec4d366ca3cf.jpeg)

kmscube app runs with no problems

**Comment by astefanutti** [comment]
Thanks a lot for the report. I think that comes from #6, more specifically from:

```c
bool is100 = strcmp(major, "1") == 0 && strcmp(minor, "00") == 0;
```

I assumed the minor version is `00`, while it seems it's `0` in the Pi  Zero 2 and Pi 3.

**Comment by gavan-x** [comment]
On the P4 it runs but with 1 2 fps... Is this performance normal?

**Comment by astefanutti** [comment]
> On the P4 it runs but with 1 2 fps... Is this performance normal?

That really depends on the complexity of the shaders and the resolution of your display device. The Pi 4 GPU is a Broadcom VideoCore VI that runs at 500 MHz, and it's easy to hit its limits as resolution increases.

Some of the shaders in the examples directory run at 60 FPS at 800x600. But others barely run at 10 FPS at that resolution.

**Comment by gavan-x** [comment]
Was at a lower resolution and the stripes example was running at 2 fps on a pi4.. I strongly suggest you test it on the latest Bullseye.

**Comment by astefanutti** [comment]
That's what I get on a Full HD (1920x1080) display:

```
$ ./glsl examples/stripey_torus_interior.glsl
Rendered 12 frames in 4.466593 sec (2.686611 fps)
```

On a RPi 4 with:

```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

$ cat /etc/debian_version
11.5
```

Note that I've increased the GPU memory setting to 128 MB.

I'm also thinking an option could be added to downscale the resolution somehow.

**Comment by gavan-x** [comment]
I'd recommend finding a setting so at least one of the example runs at 30fps.

**Comment by astefanutti** [comment]
Here is what I get with the `creation_by_silexars.glsl` examples at Full HD on the RPi 4: 

```
$ ./glsl examples/creation_by_silexars.glsl
Rendered 61 frames in 2.033252 sec (30.001202 fps)
```

Could you try that one and see what you get?

**Comment by gavan-x** [comment]
Will do but could you also make the changes and and suggest an example that should run at 30fps on a pi zero 2 w?

**Comment by astefanutti** [comment]
I've created PR #9 that adds an example that's quite simple and runs at 30 FPS full HD on the RPi 4.

Before I get a proper fix for the ES 1.00 issue, you could try with the commit before #6, i.e.,   
99510608a4fa3306460d3922befb6d4e4a34674f.

Out of curiosity, what's your resolution? I might find a display that matches so I can try on my side too.

**Comment by gavan-x** [comment]
Are you on discord?

**Comment by astefanutti** [comment]
This should be fixed with #10.

I've tested it on a Raspberry Pi Zero W:

```
$ ./glsl examples/old_skool_3d_driving.glsl 
===================================
OpenGL ES 2.x information:
  version: "OpenGL ES 2.0 Mesa 19.3.2"
  shading language version: "OpenGL ES GLSL ES 1.0.16"
  vendor: "Broadcom"
  renderer: "VC4 V3D 2.1"
===================================
Detected GLSL version from OpenGL ES GLSL ES 1.0.16
Use GLSL version directive: #version 100
Rendered 61 frames in 2.033280 sec (30.000792 fps)
Rendered 122 frames in 4.066564 sec (30.000758 fps)
Rendered 183 frames in 6.099861 sec (30.000684 fps)
```

The `examples/old_skool_3d_driving.glsl` shader runs at 30 FPS on a Full HD (1920x1080) display.

**Comment by gavan1** [comment]
I’m still getting the error on another RPI 0 W2.

has the
`bool is100 = strcmp(major, "1") == 0 && strcmp(minor, "00") == 0;`

update been made?
